In [1]:
import numpy as np
X=np.array([[2],[3]])
print("X is \n")
print((X))
y=np.array([1])
print("\n y is \n")
print(y)

X is 

[[2]
 [3]]

 y is 

[1]


In [2]:
print("Setting initial weights w1 = 0.5, w2 = 0.3, w3 = 0.2, w4 = 0.1, w5 = 0.3 and w6 = 0.4")
wh1=np.array([[0.5,0.2],[0.3,0.1]], dtype=float)
print(wh1)


Setting initial weights w1 = 0.5, w2 = 0.3, w3 = 0.2, w4 = 0.1, w5 = 0.3 and w6 = 0.4
[[0.5 0.2]
 [0.3 0.1]]


In [3]:
print("Hidden Layer 1")
#tmp = X.T
hidden_layer_input= X.T.dot(wh1)
print(hidden_layer_input)

Hidden Layer 1
[[1.9 0.7]]


In [4]:
print("Setting 2nd layer weights wh2,  w5 = 0.3 and w6 = 0.4")
wh2=np.array([[0.3],[0.4]], dtype=float)
print(wh2)


Setting 2nd layer weights wh2,  w5 = 0.3 and w6 = 0.4
[[0.3]
 [0.4]]


In [5]:
print("Predicted Output..")
forward_out= hidden_layer_input.dot(wh2)
print(forward_out)

Predicted Output..
[[0.85]]


In [6]:
print("Calculating Error")
#Error=1/2 * ((forward_out - y) ^ 2)
Error = 1/2 * (np.subtract(forward_out, y) ** 2)
print(Error)

Calculating Error
[[0.01125]]


In [7]:
print("Backward Pass..")
print()
print("delta = prediction - actual")
delta= np.subtract(forward_out, y)
print(delta)
print()
print()
print("Learning rate")
a=0.05
print(a)


Backward Pass..

delta = prediction - actual
[[-0.15]]


Learning rate
0.05


In [8]:
print("Calculating new weights..")
print("w5, w6")

tmp1 = ((a * delta) * hidden_layer_input.T)
print(tmp1)
#wh2_new =  np.subtract(wh2, tmp1)
wh2_new= wh2 - tmp1
print()
print(wh2_new)

Calculating new weights..
w5, w6
[[-0.01425]
 [-0.00525]]

[[0.31425]
 [0.40525]]


In [9]:
print("w1, w2, w3, w4")

tmp2 = ((a * delta) * X.dot(wh2.T))
print(tmp2)
#wh1_new =  np.subtract(wh1, tmp2)
wh1_new= wh1 - tmp2
print()
print(wh1_new)

w1, w2, w3, w4
[[-0.0045  -0.006  ]
 [-0.00675 -0.009  ]]

[[0.5045  0.206  ]
 [0.30675 0.109  ]]


In [10]:
print("Now, using the new weights we will repeat the forward pass")
print("Calculating 1st hidden layer values")
hidden_layer_input_fw= X.T.dot(wh1_new)
print(hidden_layer_input_fw)

Now, using the new weights we will repeat the forward pass
Calculating 1st hidden layer values
[[1.92925 0.739  ]]


In [11]:
print("Calculating new output ")
 
forward_out_2= hidden_layer_input_fw.dot(wh2_new)
print(forward_out_2)

Calculating new output 
[[0.90574656]]
