#ASSIGNMENT2A#

#Backpropagation Step by Step#


If you are building your own neural network, you will definitely need to understand how to train it. 
Backpropagation is a commonly used technique for training neural network. 
There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.

##Overview##

In this post, we will build a neural network with three layers:

Input layer with two inputs neurons.

One hidden layer with two neurons.

Output layer with a single neuron

![Image](http://hmkcode.github.io/images/ai/nn1.png)


##Weights, weights, weights ##

Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following: w1 = 0.5, w2 = 0.3, w3 = 0.2, w4 = 0.1, w5 = 0.3 and w6 = 0.4

![Image2](https://github.com/rraghu214/MLBLR-EIP3.0/blob/master/Assignments/Assignment2/Archive/Image2.JPG?raw=true)



##Dataset##

Our dataset has one sample with two inputs and one output.

![Image3](http://hmkcode.github.io/images/ai/bp_dataset.png)


Our single sample is as following inputs=[2, 3] and output=[1]

![Image4](http://hmkcode.github.io/images/ai/bp_sample.png)



##Forward Pass##

We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer.


![Image5](https://github.com/rraghu214/MLBLR-EIP3.0/blob/master/Assignments/Assignment2/Archive/Image5.JPG?raw=true)


##Calculating Error##
Now, it’s time to find out how our network performed by calculating the difference between the actual output and predicted one. It’s clear that our network output, or prediction, is not even close to actual output. We can calculate the difference or the error as following.

![Image6](https://github.com/rraghu214/MLBLR-EIP3.0/blob/master/Assignments/Assignment2/Archive/Image6.JPG?raw=true)



## Reducing Error ##

Our main goal of the training is to reduce the error or the difference between prediction and actual output. Since actual output is constant, “not changing”, the only way to reduce the error is to change prediction value. The question now is, how to change prediction value?

By decomposing prediction into its basic elements we can find that weights are the variable elements affecting prediction value. In other words, in order to change prediction value, we need to change weights values.

![Image7](http://hmkcode.github.io/images/ai/bp_prediction_elements.png)


```
The question now is how to change\update the weights value so that the error is reduced?
The answer is Backpropagation!
```


##Backpropagation##
Backpropagation short for “backward propagation of errors”, is a mechanism used to update the weights using gradient descent. It calculates the gradient of the error function with respect to the neural network’s weights. The calculation proceeds backwards through the network.

```
Gradient descent is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point.
```

![Image8](http://hmkcode.github.io/images/ai/bp_update_formula.png)


For example, to update ```w6``` , we take the current w6 and subtract the partial derivative of error function with respect to ```w6```. Optionally, we multiply the derivative of the error function by a selected number to make sure that the new updated weight is minimizing the error function; this number is called learning rate.


![Image9](http://hmkcode.github.io/images/ai/bp_w6_update.png)



The derivation of the error function is evaluated by applying the chain rule as following


![Image 10](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w6.png)


So to update w6 we can apply the following formula


![Image11](http://hmkcode.github.io/images/ai/bp_w6_update_closed_form.png)

Similarly, we can derive the update formula for w5 and any other weights existing between the output and the hidden layer.

![Image12](http://hmkcode.github.io/images/ai/bp_w5_update_closed_form.png)

However, when moving backward to update w1, w2, w3 and w4 existing between input and hidden layer, the partial derivative for the error function with respect to w1, for example, will be as following.

![Image13](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w1.png)

We can find the update formula for the remaining weights w2, w3 and w4 in the same way.

In summary, the update formulas for all weights will be as following:

![Image14](http://hmkcode.github.io/images/ai/bp_update_all_weights.png)

We can rewrite the update formulas in matrices as following

![Image15](http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png)




##Backward Pass##

Using derived formulas we can find the new weights.

``` Learning rate: is a hyperparameter which means that we need to manually guess its value. ```


(  Delta = prediction - actual )
$$ \Delta = 0.85 - 1.0 = -0.15   $$

(Learning rate, we smartly guess the number) 

$$ a=0.05 $$ 


$$ $$



$$\begin{pmatrix}W5 \\\ W6 \end{pmatrix}  =  \begin{pmatrix}0.3 \\\ 0.4 \end{pmatrix} - 0.05 (-0.15)   \begin{pmatrix}1.9 \\\ 0.7 \end{pmatrix}  = \begin{pmatrix}0.3 \\\ 0.4 \end{pmatrix} - \begin{pmatrix} -0.014 \\\ -0.005 \end{pmatrix}  =  \begin{pmatrix}0.314 \\\ 0.405 \end{pmatrix}  $$


$$\begin{pmatrix}W1 & W3 \\\ W2 & W4 \end{pmatrix}  =  \begin{pmatrix}0.5 & 0.2  \\\ 0.3&0.1 \end{pmatrix} - 0.05 (-0.15)   \begin{pmatrix}2 \\\ 3 \end{pmatrix} .  \begin{pmatrix} 0.3& 0.4 \end{pmatrix}  =  \begin{pmatrix}0.5 & 0.2  \\\ 0.3&0.1 \end{pmatrix} - \begin{pmatrix}0.004 & 0.006  \\\ 0.007&0.01 \end{pmatrix}  = \begin{pmatrix}0.496 & 0.194  \\\ 0.293&0.09 \end{pmatrix}$$


Now, using the new weights we will repeat the forward passed

![Image17](https://github.com/rraghu214/MLBLR-EIP3.0/blob/master/Assignments/Assignment2/Archive/Image17.JPG?raw=true)



We can notice that the prediction 0.907 is a little bit closer to actual output than the previously predicted one 0.85. We can repeat the same process of backward and forward pass until error is close or equal to zero.



#Assignment 2B#


In [1]:
import numpy as np
X=np.array([[2],[3]])
print("X is \n")
print((X))
y=np.array([1])
print("\n y is \n")
print(y)

X is 

[[2]
 [3]]

 y is 

[1]


In [2]:
print("Setting initial weights w1 = 0.5, w2 = 0.3, w3 = 0.2, w4 = 0.1, w5 = 0.3 and w6 = 0.4")
wh1=np.array([[0.5,0.2],[0.3,0.1]], dtype=float)
print(wh1)


Setting initial weights w1 = 0.5, w2 = 0.3, w3 = 0.2, w4 = 0.1, w5 = 0.3 and w6 = 0.4
[[0.5 0.2]
 [0.3 0.1]]


In [3]:
print("Hidden Layer 1")
#tmp = X.T
hidden_layer_input= X.T.dot(wh1)
print(hidden_layer_input)

Hidden Layer 1
[[1.9 0.7]]


In [4]:
print("Setting 2nd layer weights wh2,  w5 = 0.3 and w6 = 0.4")
wh2=np.array([[0.3],[0.4]], dtype=float)
print(wh2)


Setting 2nd layer weights wh2,  w5 = 0.3 and w6 = 0.4
[[0.3]
 [0.4]]


In [5]:
print("Predicted Output..")
forward_out= hidden_layer_input.dot(wh2)
print(forward_out)

Predicted Output..
[[0.85]]


In [6]:
print("Calculating Error")
#Error=1/2 * ((forward_out - y) ^ 2)
Error = 1/2 * (np.subtract(forward_out, y) ** 2)
print(Error)

Calculating Error
[[0.01125]]


In [7]:
print("Backward Pass..")
print()
print("delta = prediction - actual")
delta= np.subtract(forward_out, y)
print(delta)
print()
print()
print("Learning rate")
a=0.05
print(a)


Backward Pass..

delta = prediction - actual
[[-0.15]]


Learning rate
0.05


In [8]:
print("Calculating new weights..")
print("w5, w6")

tmp1 = ((a * delta) * hidden_layer_input.T)
print(tmp1)
#wh2_new =  np.subtract(wh2, tmp1)
wh2_new= wh2 - tmp1
print()
print(wh2_new)

Calculating new weights..
w5, w6
[[-0.01425]
 [-0.00525]]

[[0.31425]
 [0.40525]]


In [9]:
print("w1, w2, w3, w4")

tmp2 = ((a * delta) * X.dot(wh2.T))
print(tmp2)
#wh1_new =  np.subtract(wh1, tmp2)
wh1_new= wh1 - tmp2
print()
print(wh1_new)

w1, w2, w3, w4
[[-0.0045  -0.006  ]
 [-0.00675 -0.009  ]]

[[0.5045  0.206  ]
 [0.30675 0.109  ]]


In [10]:
print("Now, using the new weights we will repeat the forward pass")
print("Calculating 1st hidden layer values")
hidden_layer_input_fw= X.T.dot(wh1_new)
print(hidden_layer_input_fw)

Now, using the new weights we will repeat the forward pass
Calculating 1st hidden layer values
[[1.92925 0.739  ]]


In [11]:
print("Calculating new output ")
 
forward_out_2= hidden_layer_input_fw.dot(wh2_new)
print(forward_out_2)

Calculating new output 
[[0.90574656]]
